title: Free Responsive HTML5/CSS3 Template
author:
  name: Peter Finla
metadata:
    description: 'An exclusive HTML5/CSS3 freebie by Peter Finlan, for Codrops.'

# Header customization
header:
  title: Hi. I'm Thomas Vuillaume, astro-physics-data-scientist. Definitely scientist.
  description: I currently hold a postdoc position at LAPP, CNRS, working on the development of high performance data analysis algorithms and on the data management of the upcoming astronomy infrastructures such as the [Cherenkov Telescope Array](https://www.cta-observatory.org/). I am also leading the data integration task under European mission [ASTERICS](https://www.asterics2020.eu/).
  Let's <a class="smoothscroll" href="#about">start scrolling</a> and learn more <a class="smoothscroll" href="#about">about me</a>.
copyright:
    - line: &copy; Copyright 2014 CeeVee
    - line: Design by <a title="Styleshout" href="http://www.styleshout.com/">Styleshout</a>
social:
- url: "#"
  icon: facebook
- url: "#"
  icon: twitter
- url: "#"
  icon: google-plus
- url: "#"
  icon: linkedin
- url: "#"
  icon: instagram
- url: "#"
  icon: dribbble
- url: "#"
  icon: skype


# HOW TO CREATE A VALID ID TO USE:
# Go to www.twitter.com and sign in as normal, go to your settings page.
# Go to "Widgets" on the left hand side.
# Create a new widget for what you need eg "user time line" or "search" etc.
# Feel free to check "exclude replies" if you don't want replies in results.
# Now go back to settings page, and then go back to widgets page and
# you should see the widget you just created. Click edit.
# Look at the URL in your web browser, you will see a long number like this:
# 657554810648948736
# Use this as your ID below instead!

twitter:
  id: '657554810648948736' # Your widget ID
  domId: 'tw-widget1' # HTML ID used in code
  maxTweets: 3 # How many tweets to display
  enableLinks: 'true' # Enable links
  showInteraction: 'false' # Show interaction
  showImages: 'false'  # Show images
  showUser: 'false' # Show user name
